site_name: Rebble Documentation
repo_url: https://github.com/C-D-Lewis/rebble-docs
docs_dir: source
site_dir: site

# Site navigation structure
nav:
  - index.md
  - Pebble Dev:
    - Tutorials:
      - pebble/tutorials/index.md
      - Build a Watchface in C:
        - Part 1 - Displaying the Time: pebble/tutorials/watchface-tutorial/part1.md
        - Part 2 - Customizing Your Watchface: pebble/tutorials/watchface-tutorial/part2.md
        - Part 3 - Adding Web Content: pebble/tutorials/watchface-tutorial/part3.md
        - Part 4 - Adding a Battery Bar: pebble/tutorials/watchface-tutorial/part4.md
        - Part 5 - Vibrate on Disconnect: pebble/tutorials/watchface-tutorial/part5.md
      - Build a Watchface in JS:
        - Part 1 - Displaying the Time: pebble/tutorials/js-watchface-tutorial/part1.md
        - Part 2 - Adding Web Content: pebble/tutorials/js-watchface-tutorial/part2.md
      - Advanced Tutorials:
        - pebble/tutorials/advanced/vector-animations.md
    - Guides:
      - pebble/guides/index.md
      - App Resources:
        - pebble/guides/app-resources/index.md
        - App Assets: pebble/guides/app-resources/app-assets.md
        - Animated Images: pebble/guides/app-resources/animated-images.md
        - Converting SVG to PDC: pebble/guides/app-resources/converting-svg-to-pdc.md
        - Fonts: pebble/guides/app-resources/fonts.md
        - Images: pebble/guides/app-resources/images.md
        - Pebble Draw Command File Format: pebble/guides/app-resources/pdc-format.md
        - Platform Specific Resources: pebble/guides/app-resources/platform-specific.md
        - Raw Data Files: pebble/guides/app-resources/raw-data-files.md
        - System Fonts: pebble/guides/app-resources/system-fonts.md
  - Rebble:
    - rebble/index.md

# Site theme
theme:
  name: material
  favicon: assets/images/rebble-logo.png

  # Material theme features
  features:
    - navigation.tracking
    - navigation.path
    - navigation.tabs
    - content.code.copy
  logo: assets/images/rebble-logo.png
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to system preference\

# MkDocs markdown extensions
markdown_extensions:
  - toc:
      permalink: "#"
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list

# MkDocs plugins
plugins:
  - search
  - offline # Work offline (except some features)

# Extra MkDocs configuration
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pebble-dev
    - icon: fontawesome/brands/discord
      link: https://rebble.io/discord

# Extra custom CSS
extra_css:
  - stylesheets/extra.css
